# Generated by Django 4.2.7 on 2023-11-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$p9rP0IcDZCHnFTV783aJAV$g1duqr1MPSBu23spp3vzJO74uWDlGhfb5vRmxMRDTQM=', max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='123-456-7890', max_length=20),
        ),
    ]
