# Generated by Django 4.2.7 on 2023-11-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_website', '0002_remove_member_firstname_remove_member_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$E5gtoG03xXmpHQEROwWzkx$h5ELiJeYJMCGgfr5DcUGrHwBoiXm5Ou5KQdyxLgYr5o=', max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
