# Generated by Django 4.2.7 on 2023-11-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_website', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$tMjru38oOlScobxjEiOmma$3RwBJOCOimFPkN6BPOLZEZYH2nXSuLUxMxJJx8O8ZbQ=', max_length=128),
        ),
    ]
